[features]
seeds = false
[programs.localnet]
programs = "85EZivKT8uvAaphRcUfaN15Wu9PUL4eXBSh28PPDaTAE"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/throwbackjams/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
